//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratorioEntities : DbContext
    {
        public LaboratorioEntities()
            : base("name=LaboratorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exame> Exame { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<OrdemServico> OrdemServico { get; set; }
        public virtual DbSet<OrdemServicoExame> OrdemServicoExame { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<PostoColeta> PostoColeta { get; set; }
    }
}
