//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoExame
    {
        public int OrdemServicoExameId { get; set; }
        public Nullable<int> OrdemServicoId { get; set; }
        public Nullable<int> ExameId { get; set; }
        public Nullable<decimal> Preco { get; set; }
    
        public virtual Exame Exame { get; set; }
        public virtual OrdemServico OrdemServico { get; set; }
    }
}
