//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServico()
        {
            this.OrdemServicoExame = new HashSet<OrdemServicoExame>();
        }
    
        public int OrdemServicoId { get; set; }
        public int PacienteId { get; set; }
        public string Convenio { get; set; }
        public int PostoColetaId { get; set; }
        public int MedicoId { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual PostoColeta PostoColeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoExame> OrdemServicoExame { get; set; }
    }
}
